name: xmonad-config
version: "1.0"
synopsis: Emil Segerbäck's xmonad configuration
author: Emil Segerbäck
dependencies:
- base
- containers
- xmonad
- xmonad-contrib
executables:
  custom-xmonad:
    main: xmonad.hs
    source-dirs: .
    ghc-options:
    - -Wall
